### ISSUE TITLE
请问一下mirai-api-http报错404怎么回事

### ISSUE THREAD

**Issue by wuchen4588** [GardenHamster/Theresa3rd-Bot#17]
2023-01-06 18:18:09,276 [12] ERROR ConsoleLog - The server returned status code '404' when status code '101' was expected.
还不能使用机器人收到QQ消息

**Comment by GardenHamster** [comment]
mirai-http-api配置不对，把官方的配置全部复制过来重新改一遍

**Comment by GardenHamster** [comment]
[https://github.com/project-mirai/mirai-api-http#settingyml模板](https://github.com/project-mirai/mirai-api-http#settingyml%E6%A8%A1%E6%9D%BF)

**Comment by wuchen4588** [comment]
![4HO)4K%VA6WQF5~251_PSOR](https://user-images.githubusercontent.com/60568101/211000847-1a5b925f-702a-4b6c-ba3a-91feb769ab33.png)

![J$MSUUBF9`U3CKKS@C$MJ(6](https://user-images.githubusercontent.com/60568101/211000859-de93bafe-6ff6-48de-8b51-601f1b1bd521.png)
已确认配置没问题

**Comment by GardenHamster** [comment]
adapters漏了ws

**Comment by GardenHamster** [comment]
```yml
## 配置文件中的值，全为默认值

## 启用的 adapter, 内置有 http, ws, reverse-ws, webhook
adapters:
  - http
  - ws

## 是否开启认证流程, 若为 true 则建立连接时需要验证 verifyKey
## 建议公网连接时开启
enableVerify: true
verifyKey: 1234567890

## 开启一些调试信息
debug: false

## 是否开启单 session 模式, 若为 true，则自动创建 session 绑定 console 中登录的 bot
## 开启后，接口中任何 sessionKey 不需要传递参数
## 若 console 中有多个 bot 登录，则行为未定义
## 确保 console 中只有一个 bot 登录时启用
singleMode: false

## 历史消息的缓存大小
## 同时，也是 http adapter 的消息队列容量
cacheSize: 4096

## adapter 的单独配置，键名与 adapters 项配置相同
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8080
    cors: ["*"]
    unreadQueueMaxSize: 100
  
  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1
```
